project:
  type: website

website:
  title: "MSA 2024 Hackers"
  page-navigation: true
  sidebar:
    style: docked
    contents: pycheatsheet
  navbar:
    right:
      - about.qmd
      - href: pycheatsheet/index.qmd
        text: Python Cheatsheet
      - icon: github
        href: https://github.com/msa2024-hackers/2024-projects-website
  page-footer: Made with ❤️ by the MSA Class of 2024

format:
  html:
    toc: true
    number-sections: true
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
editor:
  render-on-save: true