project:
  type: website

website:
  title: "MSA 2024 Hackers"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  page-footer: Made with ❤️ by the MSA Class of 2024

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
editor:
  render-on-save: true